# Generated by Django 6.0.6 on 2026-06-14 18:40

import django.db.models.deletion
import soutenances.models
from django.conf import settings
from django.db import migrations, models


def migrate_existing_requests(apps, schema_editor):
    PFERequest = apps.get_model('soutenances', 'PFERequest')

    status_map = {
        'pending': 'pending_professor',
        'refused': 'refused_by_admin',
        'accepted': 'accepted',
    }

    for request in PFERequest.objects.select_related('student').all():
        changed = []

        if not request.authorization_document and request.fiche_demande:
            request.authorization_document = request.fiche_demande
            changed.append('authorization_document')
        if not request.rapport_stage and request.rapport_pfe:
            request.rapport_stage = request.rapport_pfe
            changed.append('rapport_stage')

        new_status = status_map.get(request.status)
        if new_status and new_status != request.status:
            request.status = new_status
            changed.append('status')

        if request.status == 'accepted':
            if not request.reviewed_by_professor_id:
                request.reviewed_by_professor_id = request.student.encadrant_id
                changed.append('reviewed_by_professor')
            if not request.professor_reviewed_at:
                request.professor_reviewed_at = request.reviewed_at or request.submitted_at
                changed.append('professor_reviewed_at')

        if request.status in {'accepted', 'refused_by_admin'}:
            if not request.reviewed_by_admin_id and request.reviewed_by_id:
                request.reviewed_by_admin_id = request.reviewed_by_id
                changed.append('reviewed_by_admin')
            if not request.admin_reviewed_at:
                request.admin_reviewed_at = request.reviewed_at
                changed.append('admin_reviewed_at')

        if changed:
            request.save(update_fields=changed)


class Migration(migrations.Migration):

    dependencies = [
        ('professors', '0002_alter_professorprofile_user_professoravailability'),
        ('soutenances', '0003_pfe_request_fiche_evaluation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='pferequest',
            name='admin_reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pferequest',
            name='authorization_document',
            field=models.FileField(blank=True, null=True, upload_to=soutenances.models.authorization_upload_path),
        ),
        migrations.AddField(
            model_name='pferequest',
            name='professor_comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pferequest',
            name='professor_reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pferequest',
            name='rapport_stage',
            field=models.FileField(blank=True, null=True, upload_to=soutenances.models.rapport_stage_upload_path),
        ),
        migrations.AddField(
            model_name='pferequest',
            name='reviewed_by_admin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_reviewed_pfe_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pferequest',
            name='reviewed_by_professor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_pfe_requests', to='professors.professorprofile'),
        ),
        migrations.AddField(
            model_name='result',
            name='has_note_gap_alert',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='result',
            name='note_gap_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='pferequest',
            name='fiche_demande',
            field=models.FileField(blank=True, null=True, upload_to=soutenances.models.fiche_upload_path),
        ),
        migrations.AlterField(
            model_name='pferequest',
            name='rapport_pfe',
            field=models.FileField(blank=True, null=True, upload_to=soutenances.models.rapport_upload_path),
        ),
        migrations.AlterField(
            model_name='pferequest',
            name='status',
            field=models.CharField(choices=[('pending_professor', 'En attente de validation encadrant'), ('refused_by_professor', "Refusee par l'encadrant"), ('pending_admin', 'En attente administration'), ('refused_by_admin', "Refusee par l'administration"), ('accepted', 'Acceptee')], default='pending_professor', max_length=30),
        ),
        migrations.RunPython(migrate_existing_requests, migrations.RunPython.noop),
        migrations.CreateModel(
            name='Evaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rapport_note', models.DecimalField(decimal_places=2, max_digits=5)),
                ('presentation_note', models.DecimalField(decimal_places=2, max_digits=5)),
                ('questions_note', models.DecimalField(decimal_places=2, max_digits=5)),
                ('final_note', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('is_submitted', models.BooleanField(default=False)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('is_locked', models.BooleanField(default=False)),
                ('unlocked_at', models.DateTimeField(blank=True, null=True)),
                ('jury_student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='soutenances.jurystudent')),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='given_evaluations', to='professors.professorprofile')),
                ('unlocked_by_admin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='unlocked_evaluations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('jury_student', 'professor')},
            },
        ),
    ]
