# Generated by Django 5.2.14 on 2026-06-14 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("soutenances", "0005_alter_deadline_id_alter_defenseschedule_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pferequest",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending_professor", "En attente de validation encadrant"),
                    ("refused_by_professor", "Refusée par l’encadrant"),
                    ("pending_admin", "En attente administration"),
                    ("refused_by_admin", "Refusée par l’administration"),
                    ("accepted", "Acceptée"),
                ],
                default="pending_professor",
                max_length=30,
            ),
        ),
    ]
