# Generated by Django 5.2.14 on 2026-06-14 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("soutenances", "0006_alter_pferequest_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="defenseschedule",
            name="duration_minutes",
            field=models.PositiveIntegerField(default=30),
        ),
    ]
