# Generated by Django 5.2.14 on 2026-06-16 02:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("soutenances", "0008_jurystudent_president_alter_deadline_id_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="jurystudent",
            name="presentation_started",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="jurystudent",
            name="presentation_started_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="jurystudent",
            name="presentation_started_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="started_presentations",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
