# Generated by Django 6.0.6 on 2026-06-17 18:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("soutenances", "0009_jurystudent_presentation_started_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="jurystudent",
            name="pfe_soutenable_decided_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="jurystudent",
            name="pfe_soutenable_decided_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="pfe_soutenable_decisions",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Décidé par",
            ),
        ),
        migrations.AddField(
            model_name="jurystudent",
            name="pfe_soutenable_status",
            field=models.CharField(
                choices=[
                    ("pending", "Décision non prise"),
                    ("soutenable", "PFE soutenable"),
                    ("non_soutenable", "PFE non soutenable"),
                ],
                default="pending",
                max_length=20,
                verbose_name="Décision soutenable",
            ),
        ),
    ]
