# Generated by Django 6.0.6 on 2026-06-18 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soutenances', '0010_pfe_soutenable_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pferequest',
            name='status',
            field=models.CharField(choices=[('pending_professor', 'En attente de validation encadrant'), ('refused_by_professor', 'Refusée par l’encadrant'), ('pending_admin', "En attente du département de l'IUP"), ('refused_by_admin', "Refusée par le département de l'IUP"), ('accepted', 'Acceptée')], default='pending_professor', max_length=30),
        ),
    ]
