# Generated by Django 6.0.6 on 2026-06-19 12:20

import soutenances.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soutenances', '0011_alter_pferequest_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='pferequest',
            name='attestation_stage',
            field=models.FileField(blank=True, null=True, upload_to=soutenances.models.attestation_stage_upload_path),
        ),
    ]
