# Generated by Django 6.0.6 on 2026-06-19 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soutenances', '0012_pferequest_attestation_stage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='defenseschedule',
            name='duration_minutes',
            field=models.PositiveIntegerField(default=20),
        ),
    ]
