# Generated by Django 6.0.6 on 2026-06-20 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soutenances', '0016_planning_contiguous_20min'),
    ]

    operations = [
        migrations.AddField(
            model_name='pferequest',
            name='reupload_comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pferequest',
            name='reupload_document',
            field=models.CharField(blank=True, choices=[('authorization', 'Autorisation de soutenance'), ('attestation', 'Attestation de stage'), ('rapport', 'Rapport de stage')], default='', max_length=20),
        ),
    ]
