# Generated by Django 6.0.6 on 2026-06-28 19:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professors', '0004_alter_professoravailability_id_and_more'),
        ('soutenances', '0017_pferequest_reupload_comment_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FiliereExpert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filiere', models.CharField(choices=[('', 'Non renseignée'), ('FINTECH', 'FINTECH'), ('DS', 'DS'), ('MAN', 'MAN'), ('LGTR', 'LGTR'), ('RXTL', 'RXTL'), ('MAEF', 'MAEF')], max_length=20)),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expert_filieres', to='professors.professorprofile')),
            ],
            options={
                'verbose_name': 'Expert de filière',
                'verbose_name_plural': 'Experts de filière',
                'unique_together': {('filiere', 'professor')},
            },
        ),
    ]
