# Generated by Django 6.0.6 on 2026-07-01 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soutenances', '0018_filiereexpert'),
    ]

    operations = [
        migrations.AddField(
            model_name='jury',
            name='salle',
            field=models.CharField(blank=True, choices=[('', 'Non définie'), ('Amphi', 'Amphi'), ('Salle 1', 'Salle 1'), ('Salle 2', 'Salle 2'), ('Salle 3', 'Salle 3'), ('Salle 7', 'Salle 7'), ('Salle 8', 'Salle 8'), ('Salle 10', 'Salle 10')], default='', max_length=20, verbose_name='Salle'),
        ),
    ]
