# Generated by Django 6.0.6 on 2026-07-02 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soutenances', '0019_jury_salle'),
    ]

    operations = [
        migrations.AddField(
            model_name='jurystudent',
            name='encadrant_absent',
            field=models.BooleanField(default=False),
        ),
    ]
