# Generated by Django 6.0.6 on 2026-07-02 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soutenances', '0020_jurystudent_encadrant_absent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pferequest',
            name='reupload_document',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
    ]
