# Generated by Django 6.0.6 on 2026-07-03 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soutenances', '0021_alter_pferequest_reupload_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jury',
            name='salle',
            field=models.CharField(blank=True, choices=[('', 'Non définie'), ('Amphi', 'Amphi'), ('Salle 1', 'Salle 1'), ('Salle 2', 'Salle 2'), ('Salle 3', 'Salle 3'), ('Salle 4', 'Salle 4'), ('Salle 7', 'Salle 7'), ('Salle 8', 'Salle 8')], default='', max_length=20, verbose_name='Salle'),
        ),
    ]
