# Generated by Django 6.0.6 on 2026-07-03 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soutenances', '0022_alter_jury_salle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jury',
            name='salle',
            field=models.CharField(blank=True, choices=[('', 'Non définie'), ('Amphi', 'Amphi'), ('Salle 1', 'Salle 1'), ('Salle 2', 'Salle 2'), ('Salle 3', 'Salle 3'), ('Salle 4', 'Salle 4'), ('Salle 8', 'Salle 8'), ('Salle 9', 'Salle 9')], default='', max_length=20, verbose_name='Salle'),
        ),
    ]
