# Generated by Django 6.0.6 on 2026-07-03 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soutenances', '0023_alter_jury_salle'),
    ]

    operations = [
        migrations.CreateModel(
            name='GenerationReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('data', models.JSONField()),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
