# Generated by Django 6.0.6 on 2026-06-14 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='filiere',
            field=models.CharField(blank=True, choices=[('', 'Non renseignee'), ('FINTECH', 'FINTECH'), ('DS', 'DS'), ('MAN', 'MAN'), ('LGTR', 'LGTR'), ('RXTL', 'RXTL'), ('MAEF', 'MAEF')], default='', max_length=20),
        ),
    ]
