# Generated by Django 5.2.14 on 2026-06-14 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0003_alter_studentprofile_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="studentprofile",
            name="filiere",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "Non renseignée"),
                    ("FINTECH", "FINTECH"),
                    ("DS", "DS"),
                    ("MAN", "MAN"),
                    ("LGTR", "LGTR"),
                    ("RXTL", "RXTL"),
                    ("MAEF", "MAEF"),
                ],
                default="",
                max_length=20,
            ),
        ),
    ]
