# Generated by Django 5.2.14 on 2026-06-16 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0005_alter_studentprofile_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="StudentReference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("matricule", models.CharField(max_length=50, unique=True)),
                ("full_name", models.CharField(max_length=255)),
                ("filiere", models.CharField(blank=True, default="", max_length=20)),
                (
                    "encadrant_name",
                    models.CharField(blank=True, default="", max_length=255),
                ),
            ],
        ),
    ]
