# Generated by Django 5.2.14 on 2026-06-18 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0006_studentreference"),
    ]

    operations = [
        migrations.AddField(
            model_name="studentprofile",
            name="entreprise",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
    ]
