# Generated by Django 6.0.6 on 2026-06-14 18:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def copy_professor_phone_to_user(apps, schema_editor):
    ProfessorProfile = apps.get_model('professors', 'ProfessorProfile')
    CustomUser = apps.get_model('accounts', 'CustomUser')

    used_numbers = set(
        CustomUser.objects.exclude(phone_number__isnull=True)
        .exclude(phone_number='')
        .values_list('phone_number', flat=True)
    )
    for professor in ProfessorProfile.objects.select_related('user').all():
        if not professor.user_id or not professor.phone:
            continue
        user = professor.user
        if user.phone_number or professor.phone in used_numbers:
            continue
        user.phone_number = professor.phone
        user.save(update_fields=['phone_number'])
        used_numbers.add(professor.phone)


class Migration(migrations.Migration):

    dependencies = [
        ('professors', '0001_initial'),
        ('accounts', '0002_customuser_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professorprofile',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='professor_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='ProfessorAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availabilities', to='professors.professorprofile')),
            ],
            options={
                'ordering': ['date', 'start_time'],
                'unique_together': {('professor', 'date', 'start_time', 'end_time')},
            },
        ),
        migrations.RunPython(copy_professor_phone_to_user, migrations.RunPython.noop),
    ]
