# Generated by Django 5.2.14 on 2026-06-14 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("professors", "0002_alter_professorprofile_user_professoravailability"),
    ]

    operations = [
        migrations.AlterField(
            model_name="professoravailability",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="professorprofile",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
