# Generated by Django 5.2.14 on 2026-06-15 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("professors", "0003_alter_professoravailability_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="professoravailability",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="professorprofile",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
