# Generated by Django 6.0.6 on 2026-07-03 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professors', '0005_convert_availabilities_to_slots'),
    ]

    operations = [
        migrations.AddField(
            model_name='professorprofile',
            name='is_priority',
            field=models.BooleanField(default=False, verbose_name='Prof prioritaire'),
        ),
    ]
