# Generated by Django 6.0.6 on 2026-06-14 18:40

from django.db import migrations, models


def classify_existing_templates(apps, schema_editor):
    DocumentTemplate = apps.get_model('documents', 'DocumentTemplate')
    for document in DocumentTemplate.objects.all():
        haystack = f"{document.title} {document.file}".lower()
        if 'evaluation' in haystack or 'évaluation' in haystack:
            document.template_type = 'evaluation'
            document.save(update_fields=['template_type'])


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='documenttemplate',
            name='template_type',
            field=models.CharField(choices=[('student_request', 'Template demande etudiant'), ('evaluation', 'Fiche evaluation'), ('other', 'Autre')], default='student_request', max_length=30),
        ),
        migrations.RunPython(classify_existing_templates, migrations.RunPython.noop),
    ]
