# Generated by Django 6.0.6 on 2026-06-18 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0004_alter_documenttemplate_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documenttemplate',
            name='template_type',
            field=models.CharField(choices=[('student_request', 'Modèle de demande étudiant'), ('evaluation', "Fiche d'évaluation"), ('other', 'Autre')], default='student_request', max_length=30),
        ),
    ]
