from django.urls import path

from . import views


urlpatterns = [
    path("admin/demandes/", views.admin_pfe_requests, name="admin_pfe_requests"),
    path("admin/demandes/<int:pk>/", views.admin_pfe_request_detail, name="admin_pfe_request_detail"),
    path("admin/demandes/<int:pk>/accepter/", views.admin_pfe_quick_accept, name="admin_pfe_quick_accept"),
    path("admin/demandes/<int:pk>/refuser/", views.admin_pfe_quick_refuse, name="admin_pfe_quick_refuse"),
    path("admin/demandes/accepter-tout/", views.admin_pfe_accept_all, name="admin_pfe_accept_all"),
    path("admin/demandes/accepter-bloquees/", views.admin_pfe_accept_blocked, name="admin_pfe_accept_blocked"),
    path("admin/soutenance-historique/", views.admin_add_historical_defense, name="admin_add_historical_defense"),
    path("admin/deadline/", views.admin_deadline, name="admin_deadline"),
    path("admin/jurys/", views.admin_jury_list, name="admin_jury_list"),
    path("admin/jurys/generate/", views.admin_generate_juries, name="admin_generate_juries"),
    path("admin/jurys/generate-targeted/", views.admin_generate_juries_targeted, name="admin_generate_juries_targeted"),
    path("admin/jurys/experts/", views.admin_expert_groups, name="admin_expert_groups"),
    path("admin/jurys/profs-prioritaires/", views.admin_priority_professors_report, name="admin_priority_professors_report"),
    path("admin/jurys/dernier-rapport/", views.admin_last_generation_report, name="admin_last_generation_report"),
    path("admin/jurys/diagnostic/", views.admin_scheduling_diagnostic, name="admin_scheduling_diagnostic"),
    path("admin/jurys/conflits/", views.admin_jury_conflicts, name="admin_jury_conflicts"),
    path("admin/jurys/emploi-du-temps/", views.admin_timetable, name="admin_timetable"),
    path("admin/jurys/<int:pk>/export/", views.admin_jury_export, name="admin_jury_export"),
    path("admin/jurys/reordonner-horaires/", views.admin_reorder_all_schedules, name="admin_reorder_all_schedules"),
    path("admin/jurys/placer-sans-jury/", views.admin_fill_unassigned_into_juries, name="admin_fill_unassigned_into_juries"),
    path("admin/jurys/ajouter-manuel/", views.admin_jury_add_manual, name="admin_jury_add_manual"),
    path("admin/jurys/generer-par-filiere/", views.admin_generate_by_filiere, name="admin_generate_by_filiere"),
    path("admin/jurys/dernier-test-filiere/", views.admin_by_filiere_last_preview, name="admin_by_filiere_last_preview"),
    path("admin/jurys/appliquer-par-filiere/", views.admin_apply_by_filiere, name="admin_apply_by_filiere"),
    path("admin/jurys/delete-drafts/", views.admin_delete_draft_juries, name="admin_delete_draft_juries"),
    path("admin/jurys/create/", views.admin_jury_create, name="admin_jury_create"),
    path("admin/jurys/quick-create/", views.admin_jury_quick_create, name="admin_jury_quick_create"),
    path("admin/jurys/helper/slots/", views.admin_jury_helper_slots, name="admin_jury_helper_slots"),
    path("admin/jurys/helper/members/", views.admin_jury_helper_members, name="admin_jury_helper_members"),
    path("admin/jurys/<int:pk>/", views.admin_jury_detail, name="admin_jury_detail"),
    path("admin/jurys/<int:pk>/edit/", views.admin_jury_update, name="admin_jury_update"),
    path("admin/jurys/<int:pk>/delete/", views.admin_jury_delete, name="admin_jury_delete"),
    path("admin/jurys/<int:pk>/publish/", views.admin_jury_publish, name="admin_jury_publish"),
    path("admin/jurys/<int:pk>/add-student/", views.admin_jury_add_student, name="admin_jury_add_student"),
    path("admin/jurys/<int:pk>/students/<int:assignment_pk>/remove/", views.admin_jury_remove_student, name="admin_jury_remove_student"),
    path("admin/planning/", views.admin_planning, name="admin_planning"),
    path("admin/planning/generate/", views.admin_generate_planning, name="admin_generate_planning"),
    path("admin/results/", views.admin_results, name="admin_results"),
    path("admin/results/<int:pk>/publish/", views.admin_publish_result, name="admin_publish_result"),
    path("admin/evaluations/<int:pk>/unlock/", views.admin_unlock_evaluation, name="admin_unlock_evaluation"),
    path("admin/results/publish-all/", views.admin_publish_all_results, name="admin_publish_all_results"),
    path("admin/results/par-filiere/", views.admin_results_by_filiere, name="admin_results_by_filiere"),
    path("admin/results/fiche-de-notes/", views.admin_grade_sheet, name="admin_grade_sheet"),
    path("admin/exports/jurys.pdf", views.export_juries_pdf, name="export_juries_pdf"),
    path("admin/exports/planning.pdf", views.export_planning_pdf, name="export_planning_pdf"),
    path("admin/exports/results.pdf", views.export_results_pdf, name="export_results_pdf"),
    path("admin/exports/pv/<int:pk>.pdf", views.export_student_pv_pdf, name="export_student_pv_pdf"),
    path("exports/fiche-evaluation/<int:pk>.pdf", views.export_evaluation_fiche_pdf, name="export_evaluation_fiche_pdf"),
]
